Fixed up the Home fragment in regards to the backend and made it look better
CMPUT301W24T04/QrazyQRsRUs pull request #93
Opened 2024-03-24 05:16 UTC by Mikael-UofA

More specifically I fixed up the issue where the events you checked in weren't displayed

2024-03-24 13:24 UTC, john00003 requested changes
![image](https://github.com/CMPUT301W24T04/QrazyQRsRUs/assets/121990449/78a5b1ff-c184-466c-b820-4daa79fe23e7)

LOL
once this is fixed, everything else looks great. thanks Mikael!

2024-03-24 20:56 UTC, Mikael-UofA commented
Fixed that

2024-03-24 20:59 UTC, john00003 approved these changes
good stuff thanks Mikael

2024-03-26 02:17 UTC, icansingh approved these changes

2024-03-26 02:18 UTC, merged